#!/bin/sh
export DISPLAY=`w | grep klanc | cut -d' ' -f5`
export XAUTHORITY=/home/klanc/.Xauthority
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"
/home/klanc/.scripts/udev/switch_inject &
